### PR TITLE
Cleaned it up a bit

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
- Added Javadoc. A lot.
- Removed some unecessary statics and public variables.
- Changed some variable names from things like "fc" to "fileChooser" and stuff like that.
- Changed some anonymous inner classes to lambdas (action listener)
- Enforced the DRY pattern in the Logger class.
- Changed the Date format in the Logger class, using the Java 8 Time API. Why? Don't really know.

As far as I know I changed no logic, just how the code was presented.

Sorry about the indentation, what do you use (I use Tabs only)?
It seems to render the github compare view a bit clueless.

Still seems to work surprisingly.

Hope I didn't mess anything up doing this pull request...

### CODE REVIEW

**Comment by ArsenArsen** [comment]
Oooooor CTRL+A and then CTRL+I

**Comment by I-Al-Istannen** [comment]
I used CTRL+A then CTRL+SHIFT+F, which does that too. It is nicely formatted for me, but bwfcwalshy seems to use a different formatting for his code. His looked absolutely bad on my eclipse and wasn't even correctly indented, so I needed to use my own. 

Would be great if there was an easy way to use the same formatter.

**Comment by bwfcwalshyPluginDev** [comment]
I use tab too, from what I can see you seem to have indented everything twice. It looks completely fine on my Eclipse. I never use the Eclipse reformatter as it only adds the brackets on the next line and puts some things on a new line which I don't like there.

**Comment by I-Al-Istannen** [comment]
It is indented once in my eclipse...
[Here](http://imgur.com/6p6OVMH) is a picture. I selected one tab.
Strange.

I normally don't use the formatter too, but it was more convenient in this case. You can even see the `@formatter:off` tags in the Checks enum, as it totally destroyed the order otherwise xD

I am sorry about the formatting, but I don't really see how I could change it, as it looks good in my eclipse and Notepad++.
Hopefully won't prevent you from looking at the changes though :wink:

**Comment by bwfcwalshyPluginDev** [comment]
Yeah I'll have a look in my Eclipse when I can and see what is happening. In GitHib it looks like everything was tabbed again. As for your changes, I've seen and like but the thing that has stopped me pushing currently is you have made it Java 8, this project is in Java 7. (Java 8 is better no doubt about that) My Eclipse workspace (Software one) is Java 7 by default for other projects so I would need to make this one Java 8 and of course anyone using this (Curse, Bukkit staff, trusted members whatever) would also need Java 8. Most people do not have Java 8 despite Java 9 being heavily developed. We will need to make sure that the README says it is Java 8 and if we add a Pom.xml for those Maven people it points to Java 8 (You need to do that right?)

**Comment by I-Al-Istannen** [comment]
Oh, that is totally understandable. Didn't even think of it...

Just for your information: The Predicate was already Java 8 too (sorry). It just makes some things easier.

I don't know any recent statistics about the Java version, but 8 is out since 18 March 2014. God, if people could update xD Maybe they have good reasons for it though.

And I have never worked with Maven, so I am no help there either :/

But have a nice day and take your time ;)

**Comment by bwfcwalshyPluginDev** [comment]
Look at Arsen's recent pull request on the test branch, he has reformatted it to what it was like before as well :p 1 tab, yours look like they have 2.

**Comment by ArsenArsen** [comment]
Can you change the request so it goes into the test branch @I-Al-Istannen ? I need to see are there any complex merges that aren't supported by octopus.

**Comment by I-Al-Istannen** [comment]
No idea how to do this :/

**Comment by ArsenArsen** [comment]
@I-Al-Istannen ooh.. Try to make a new pull request to branch test

**Comment by ArsenArsen** [comment]
Merged in #cbf0070

**Pull request closed without merging**
